### ISSUE TITLE
Getting Blank Prediction Images

### ISSUE THREAD

**Issue by nama1arpit** [lauraset/BuildingHeightModel#2]
First of all, thanks for your efforts and an interesting work. I have been trying to running your model using `pred_zy3bh_tlcnetU_mux.py` file but after a successful run the images in the `pred/` folder are blank like the following:
![image](https://user-images.githubusercontent.com/36475839/187684788-2fa022f1-7298-4d2e-9383-20c2ea18a567.png)

**Comment by lauraset** [comment]
hello, @nama1arpit . Sorry for the late reply and I am busy with finding a job. 
The result you show is right. For the segmentation map, the values of buildings and non-buildings are 1 and 0, respectively.
You can add this line (see the following picture) in the file or show this figure in the visualization software, e.g., ENVI or QGIS.
![image](https://user-images.githubusercontent.com/39206462/195306803-4ab29172-0eae-469c-af04-7bb55b7b1f48.png)
The predicted results are uploaded in the directory `pred` and you can check it.
![image](https://user-images.githubusercontent.com/39206462/195307190-42990377-cb6a-4da8-86de-ef392bd769b4.png)

If there is any issue, please feel free to contact me by opening an issue or email (yinxcao@163.com).
