### ISSUE TITLE
如何从高德地图中获取楼层信息？

### ISSUE THREAD

**Issue by Sherlock-Sun** [lauraset/BuildingHeightModel#3]
您好！我有看到您使用了高德地图的建筑物数据集，并公开了这个数据集，但是我想知道这个数据集是如何获取的，我最近有去高德地图搜索，但是并没有找到。

**Comment by lauraset** [comment]
您好，这个数据集是公开可获取的，我当时是直接下载的别人爬取好的，如果你要自己去爬取，就需要用API去访问高德地图。
